{{- if .Values.serviceAccountRBAC.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
subjects:
- kind: ServiceAccount
  name: {{ include "call-nested" (list . "opentelemetry-collector" "opentelemetry-collector.serviceAccountName") }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: otel-collector
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
