apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.0"

dependencies:
- name: opentelemetry-collector
  version: "~0.5.9"
  repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
